name: prueba_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  provider: ^6.1.2
  firebase_messaging: ^15.1.6
  rxdart: ^0.28.0
  file_picker: ^8.1.4
  excel: ^4.0.6
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  google_api_availability: ^5.0.0
  cloud_functions: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # flutter_launcher_icons: ^0.14.3

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/iconoajs.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   web:
#     generate: true
#     image_path: "assets/images/iconoajs.png"
#     background_color: "#hexcode"
#     theme_color: "#hexcode"
#   windows:
#     generate: true
#     image_path: "assets/images/iconoajs.png"
#     icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true
  assets:
    - assets/images/iconoajs.png
