name: prueba_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  provider: ^6.1.2
  firebase_messaging: ^15.1.6
  rxdart: ^0.28.0
  file_picker: ^8.1.4
  excel: ^4.0.6
  path_provider: ^2.1.5
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  google_api_availability: ^5.0.0
  intl: ^0.19.0
  firebase_storage: ^12.3.7
  image_picker: ^1.1.2
  cloud_functions: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/iconoajs.png
